//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Barrio
    {
        public Barrio()
        {
            this.Cliente = new HashSet<Cliente>();
        }
    
        public long id { get; set; }
        public string NombreBarrio { get; set; }
        public Nullable<System.DateTime> FechaFundacion { get; set; }
        public string Descripcion { get; set; }
        public long idZona { get; set; }
    
        public virtual Zona Zona { get; set; }
        public virtual ICollection<Cliente> Cliente { get; set; }
    }
}
