//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        public long id { get; set; }
        public string Direccion { get; set; }
        public string Telefono { get; set; }
        public Nullable<long> Nit { get; set; }
        public long idRubro { get; set; }
        public long idBarrio { get; set; }
    
        public virtual Barrio Barrio { get; set; }
        public virtual Rubro Rubro { get; set; }
        public virtual Juridico Juridico { get; set; }
        public virtual Natural Natural { get; set; }
    }
}
