//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbDesarrolloSistemaISeptiembre2026Entities : DbContext
    {
        public dbDesarrolloSistemaISeptiembre2026Entities()
            : base("name=dbDesarrolloSistemaISeptiembre2026Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Barrio> Barrio { get; set; }
        public DbSet<Cliente> Cliente { get; set; }
        public DbSet<Juridico> Juridico { get; set; }
        public DbSet<Natural> Natural { get; set; }
        public DbSet<Rubro> Rubro { get; set; }
        public DbSet<Zona> Zona { get; set; }
        public DbSet<VClienteGeneral> VClienteGeneral { get; set; }
    }
}
