//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class VClienteGeneral
    {
        public long idcliente { get; set; }
        public string NombreCliente { get; set; }
        public string DocumentoIdentidad { get; set; }
        public Nullable<System.DateTime> FechaNacimiento { get; set; }
        public string Genero { get; set; }
        public string Direccion { get; set; }
        public Nullable<long> Nit { get; set; }
        public string Telefono { get; set; }
        public long idBarrio { get; set; }
        public string NombreBarrio { get; set; }
        public long idzona { get; set; }
        public string NombreZona { get; set; }
        public long idrubro { get; set; }
        public string NombreRubro { get; set; }
        public string ZonaBarrio { get; set; }
        public string TipoCliente { get; set; }
    }
}
